mkdir -p bin
clang++ $(pkg-config --cflags --libs libpulse) -lOpenCL -lclFFT -ldl -o bin/ceal -std=c++20 src/ceal.cc src/common.cc -g -fno-omit-frame-pointer

# originally generated by ccproj version 1.3
